name: new_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependency_overrides:
  meta: 1.8.0

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  scoped_model: ^2.0.0
  provider: ^6.1.1
  gap: ^3.0.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.3.1
  get_it: ^7.6.0
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  flutter_svg: ^2.0.7
  pin_code_fields: ^7.0.0
  flutter_switch: ^0.3.2
  logger: ^2.0.1
  local_auth: ^2.1.7
  shared_preferences: ^2.2.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  device_manager: ^0.0.2
  overlay_support: ^2.1.0
  flutter_pin_code_fields: ^2.2.0
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  smooth_page_indicator: ^1.1.0
  firebase_remote_config: ^4.3.8
  firebase_core: ^2.24.2
  localstorage: ^4.0.1+4
  qr_code_scanner: ^1.0.1
  image_picker: ^1.0.4
  image: ^4.1.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  currency_text_input_formatter: ^2.1.10
  collection: ^1.17.0




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  win32: ^5.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/images/
  #   - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: AkiraExpandedDemo
#      fonts:
#        - asset: assets/fonts/AkiraExpandedDemo.otf
#    - family: SpaceGrotesk
#      fonts:
#        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
#          weight: 700
#    - family: Syne
#      fonts:
#        - asset: assets/fonts/Syne-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Syne-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Syne-Bold.ttf
#          weight: 700
